spring.application.name=otpbasedlogin
spring.datasource.url=jdbc:h2:mem:otpauthdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# app settings
otp.expiry.minutes=5
otp.max-attempts=3
otp.block-minutes=10

